"""一旦voteのmodelを消す

Revision ID: 35348de668d4
Revises: 3e8ab9e46691
Create Date: 2024-08-01 07:17:19.486500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35348de668d4'
down_revision = '3e8ab9e46691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_id', table_name='votes')
    op.drop_index('ix_votes_user_id', table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='votes_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    op.create_index('ix_votes_id', 'votes', ['id'], unique=False)
    # ### end Alembic commands ###
