"""voteのモデルを変更

Revision ID: 3e8ab9e46691
Revises: e525a328076b
Create Date: 2024-07-29 09:31:01.582351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e8ab9e46691'
down_revision = 'e525a328076b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('id', sa.VARCHAR(length=255), nullable=False))
    op.add_column('votes', sa.Column('group_id', sa.VARCHAR(length=255), nullable=False))
    op.drop_index('user_id', table_name='votes')
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=True)
    op.drop_constraint('votes_ibfk_2', 'votes', type_='foreignkey')
    op.drop_constraint('votes_ibfk_1', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'groups', ['group_id'], ['id'])
    op.drop_column('votes', 'group_id_21')
    op.drop_column('votes', 'group_id_11')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('group_id_11', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('votes', sa.Column('group_id_21', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_ibfk_1', 'votes', 'groups', ['group_id_21'], ['id'])
    op.create_foreign_key('votes_ibfk_2', 'votes', 'groups', ['group_id_11'], ['id'])
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.create_index('user_id', 'votes', ['user_id'], unique=False)
    op.drop_column('votes', 'group_id')
    op.drop_column('votes', 'id')
    # ### end Alembic commands ###
