"""linktextの型をvarcharからtextに変更

Revision ID: 5e583a6e225c
Revises: 73277cc08dac
Create Date: 2024-09-23 14:59:44.935752

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e583a6e225c"
down_revision = "73277cc08dac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "grouplinks", "linktext", existing_type=sa.VARCHAR(255), type_=sa.VARCHAR(1023)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "grouplinks",
        "linktext",
        existing_type=sa.VARCHAR(1023),
        type_=sa.VARCHAR(255),
    )
    # ### end Alembic commands ###
