"""vote model再構築

Revision ID: 73277cc08dac
Revises: 35348de668d4
Create Date: 2024-08-01 07:18:08.946463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73277cc08dac'
down_revision = '35348de668d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=True)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
