"""voteのmodelを変更

Revision ID: 7daf91314cfe
Revises: e525a328076b
Create Date: 2024-07-24 09:24:53.192633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7daf91314cfe'
down_revision = 'e525a328076b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'group_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_votes_user_id', table_name='votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    op.alter_column('votes', 'group_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
