"""Newsのdetailの文字数を長くした

Revision ID: e525a328076b
Revises: b01b6794fa9c
Create Date: 2024-05-31 12:16:06.930988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e525a328076b'
down_revision = 'b01b6794fa9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
